name: 程式碼品質檢查

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: 格式檢查與靜態分析
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 設定 Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      
      - name: 檢查程式碼格式
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          
      - name: 運行 Clippy 靜態分析
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings